### ISSUE TITLE
plain output

### ISSUE THREAD

**Issue by lmj0011** [notgiorgi/node-debug-timezone#1]
I'm using node-debug-timezone in this fashion

logger.js
```js
const debug = require('debug-timezone')
const log = debug('adonuxt-rp:log', 'DD.MM.YY', 'America/Chicago') // CST
const error = debug('adonuxt-rp:error', 'DD.MM.YY', 'America/Chicago')
debug.log = console.info.bind(console) // https://www.npmjs.com/package/debug#output-streams

const logger = {
  log,
  error
}

module.exports = logger
module.exports.default = logger
```

app.js
```js

const logger = require('./logger')


logger.log('Developers! Developers! Developers!')
// Developers! Developers! Developers!'

```

When I import this into my app for use, I do not get the timestamp nor the colored coded text that's normally outputted with debug lib

**Comment by notgiorgi** [comment]
Take a look at this: https://github.com/visionmedia/debug#environment-variables

**Comment by lmj0011** [comment]
What am I suppose to get from that?

**Comment by lmj0011** [comment]
ok...What am I suppose to get from that?

**Comment by notgiorgi** [comment]
Are you setting environment variables correctly?

**Comment by lmj0011** [comment]
yes

`DEBUG=adonuxt-rp:*,eslint:*,knex:tx`

**Comment by notgiorgi** [comment]
Are you setting DEBUG_COLORS=true

Are you logging to files? If you're logging to terminal, it won't work: https://github.com/visionmedia/debug#millisecond-diff

**Comment by lmj0011** [comment]
is this what needs to be done for this lib to work?

because with `debug` colors show and I only have that `DEBUG` env var set.

![sample](https://cloud.githubusercontent.com/assets/9396189/26046316/0a3237c4-3914-11e7-9206-f99aecf8d132.png)

**Comment by notgiorgi** [comment]
Right now it shows you diffs between consequent logs, if you let stdout go to file you'll get timestamps, like this:

```
DEBUG=* node index.js >> logs.txt
```

**Comment by notgiorgi** [comment]
@lmj0011 did that help you? should I close this?

**Comment by lmj0011** [comment]
this can be closed, I need the timestamp in stdout.

I'll just continue using the debug library.
